version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./my-html:/usr/share/nginx/html
  monitor:
    image: nicolargo/glances
    pid: "host"
    ports:
      - "61208:61208"
    environment:
      - "GLANCES_OPT=-w"
